{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b385769f-a9b0-4809-abbb-869d89aa5069",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== Secure Password Manager ===\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter master password:  ········\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "1.Add  2.View  3.Delete  4.Search  5.Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose:  2\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import os\n",
    "import base64\n",
    "import hashlib\n",
    "from cryptography.fernet import Fernet, InvalidToken\n",
    "from getpass import getpass\n",
    "\n",
    "DATA_FILE = \"passwords.enc\"\n",
    "SALT_FILE = \"salt.bin\"\n",
    "\n",
    "# KEY DERIVATION \n",
    "def derive_key(password, salt):\n",
    "    key = hashlib.pbkdf2_hmac(\n",
    "        \"sha256\",\n",
    "        password.encode(),\n",
    "        salt,\n",
    "        100000\n",
    "    )\n",
    "    return base64.urlsafe_b64encode(key)\n",
    "\n",
    "#  INIT SALT \n",
    "def load_or_create_salt():\n",
    "    if not os.path.exists(SALT_FILE):\n",
    "        salt = os.urandom(16)\n",
    "        with open(SALT_FILE, \"wb\") as f:\n",
    "            f.write(salt)\n",
    "    else:\n",
    "        with open(SALT_FILE, \"rb\") as f:\n",
    "            salt = f.read()\n",
    "    return salt\n",
    "\n",
    "#  LOAD DATABASE \n",
    "def load_data(fernet):\n",
    "    if not os.path.exists(DATA_FILE):\n",
    "        return {}\n",
    "\n",
    "    try:\n",
    "        with open(DATA_FILE, \"rb\") as f:\n",
    "            encrypted = f.read()\n",
    "\n",
    "        decrypted = fernet.decrypt(encrypted).decode()\n",
    "        return json.loads(decrypted)\n",
    "\n",
    "    except InvalidToken:\n",
    "        print(\"❌ Wrong master password!\")\n",
    "        exit()\n",
    "\n",
    "    except Exception:\n",
    "        return {}\n",
    "\n",
    "#  SAVE DATABASE \n",
    "def save_data(data, fernet):\n",
    "    encrypted = fernet.encrypt(json.dumps(data, indent=2).encode())\n",
    "    with open(DATA_FILE, \"wb\") as f:\n",
    "        f.write(encrypted)\n",
    "\n",
    "#  FUNCTIONS \n",
    "def add_entry(data):\n",
    "    site = input(\"Website: \")\n",
    "    user = input(\"Username: \")\n",
    "    pwd = getpass(\"Password: \")\n",
    "\n",
    "    data[site] = {\"username\": user, \"password\": pwd}\n",
    "    print(\"✅ Saved.\")\n",
    "\n",
    "def view_entry(data):\n",
    "    site = input(\"Website to retrieve: \")\n",
    "    if site in data:\n",
    "        print(\"Username:\", data[site][\"username\"])\n",
    "        print(\"Password:\", data[site][\"password\"])\n",
    "    else:\n",
    "        print(\"❌ Not found.\")\n",
    "\n",
    "def delete_entry(data):\n",
    "    site = input(\"Website to delete: \")\n",
    "    if site in data:\n",
    "        del data[site]\n",
    "        print(\"🗑 Deleted.\")\n",
    "    else:\n",
    "        print(\"❌ Not found.\")\n",
    "\n",
    "def search_entries(data):\n",
    "    keyword = input(\"Search keyword: \").lower()\n",
    "    found = False\n",
    "    for site in data:\n",
    "        if keyword in site.lower():\n",
    "            print(f\"{site} -> {data[site]['username']}\")\n",
    "            found = True\n",
    "    if not found:\n",
    "        print(\"No matches.\")\n",
    "\n",
    "#  MAIN \n",
    "def main():\n",
    "\n",
    "    print(\"=== Secure Password Manager ===\")\n",
    "\n",
    "    salt = load_or_create_salt()\n",
    "    master = getpass(\"Enter master password: \")\n",
    "\n",
    "    key = derive_key(master, salt)\n",
    "    fernet = Fernet(key)\n",
    "\n",
    "    data = load_data(fernet)\n",
    "\n",
    "    while True:\n",
    "        print(\"\\n1.Add  2.View  3.Delete  4.Search  5.Exit\")\n",
    "        choice = input(\"Choose: \")\n",
    "\n",
    "        if choice == \"1\":\n",
    "            add_entry(data)\n",
    "            save_data(data, fernet)\n",
    "\n",
    "        elif choice == \"2\":\n",
    "            view_entry(data)\n",
    "\n",
    "        elif choice == \"3\":\n",
    "            delete_entry(data)\n",
    "            save_data(data, fernet)\n",
    "\n",
    "        elif choice == \"4\":\n",
    "            search_entries(data)\n",
    "\n",
    "        elif choice == \"5\":\n",
    "            save_data(data, fernet)\n",
    "            print(\"Goodbye.\")\n",
    "            break\n",
    "\n",
    "        else:\n",
    "            print(\"Invalid option\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9740471-451d-42d5-8c92-1af51f890c49",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
